_target_: src.logger.CometMLWriter
project_name: "neural-audio-codec"
workspace: null
run_name: null
mode: "online"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: False
id_length: 32 # length of the run_id
